---

- hosts: all
  become: true
  tasks:

  - name: install apache2
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == [ "debian" , "Ubuntu" ]


  - name: install apache and php on Fedora
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Fedora"
