---

- hosts: all
  become: true
  tasks:

  - name: install apache2
    apt:
      name: apache2
      state: latest
      update_cache: yes
    when: ansible_distribution in [ "Debian" , "Ubuntu" ]

  - name: install apache
    dnf:
      name: httpd
      state: latest
      update_cache: yes
    when: ansible_distribution == "Fedora"
